name: Deploy to EC2

on:
  push:
    branches:
      - master  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: |
        sudo apt-get update
        sudo apt-get install openssh-client -y

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa2
        chmod 600 ~/.ssh/id_rsa2
        ssh-keyscan -H ec2-54-165-255-78.compute-1.amazonaws.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy application to EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@ec2-54-165-255-78.compute-1.amazonaws.com << 'EOF'
          cd /root/hello-world-nestjs
          git pull origin master  
          npm install  
          pm2 restart app_name || pm2 start ./dist/main.js --name app_name
        EOF

