name: Deploy to EC2

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Add EC2 instance to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem -o "StrictHostKeyChecking=no" -r ./dist $EC2_USER@$EC2_HOST:/home/$EC2_USER/nestjs-hello-world
        ssh -i key.pem -o "StrictHostKeyChecking=no" $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/$EC2_USER/nestjs-hello-world
          pm2 restart nestjs-app || pm2 start dist/main.js --name nestjs-app
        EOF

